//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchiveTorrents.TorrageWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:Torrage", ConfigurationName="TorrageWS.CachePortType")]
    public interface CachePortType {
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:xmethods-delayed-quotes) of message cacheTorrentRequest does not match the default value (urn:Torrage)
        [System.ServiceModel.OperationContractAttribute(Action="urn:xmethods-delayed-quotes#cacheTorrent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ArchiveTorrents.TorrageWS.cacheTorrentResponse cacheTorrent(ArchiveTorrents.TorrageWS.cacheTorrentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:xmethods-delayed-quotes#cacheTorrent", ReplyAction="*")]
        System.Threading.Tasks.Task<ArchiveTorrents.TorrageWS.cacheTorrentResponse> cacheTorrentAsync(ArchiveTorrents.TorrageWS.cacheTorrentRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cacheTorrent", WrapperNamespace="urn:xmethods-delayed-quotes", IsWrapped=true)]
    public partial class cacheTorrentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string torrent;
        
        public cacheTorrentRequest() {
        }
        
        public cacheTorrentRequest(string torrent) {
            this.torrent = torrent;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cacheTorrentResponse", WrapperNamespace="urn:xmethods-delayed-quotes", IsWrapped=true)]
    public partial class cacheTorrentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Result;
        
        public cacheTorrentResponse() {
        }
        
        public cacheTorrentResponse(string Result) {
            this.Result = Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CachePortTypeChannel : ArchiveTorrents.TorrageWS.CachePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CachePortTypeClient : System.ServiceModel.ClientBase<ArchiveTorrents.TorrageWS.CachePortType>, ArchiveTorrents.TorrageWS.CachePortType {
        
        public CachePortTypeClient() {
        }
        
        public CachePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CachePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CachePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CachePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ArchiveTorrents.TorrageWS.cacheTorrentResponse ArchiveTorrents.TorrageWS.CachePortType.cacheTorrent(ArchiveTorrents.TorrageWS.cacheTorrentRequest request) {
            return base.Channel.cacheTorrent(request);
        }
        
        public string cacheTorrent(string torrent) {
            ArchiveTorrents.TorrageWS.cacheTorrentRequest inValue = new ArchiveTorrents.TorrageWS.cacheTorrentRequest();
            inValue.torrent = torrent;
            ArchiveTorrents.TorrageWS.cacheTorrentResponse retVal = ((ArchiveTorrents.TorrageWS.CachePortType)(this)).cacheTorrent(inValue);
            return retVal.Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ArchiveTorrents.TorrageWS.cacheTorrentResponse> ArchiveTorrents.TorrageWS.CachePortType.cacheTorrentAsync(ArchiveTorrents.TorrageWS.cacheTorrentRequest request) {
            return base.Channel.cacheTorrentAsync(request);
        }
        
        public System.Threading.Tasks.Task<ArchiveTorrents.TorrageWS.cacheTorrentResponse> cacheTorrentAsync(string torrent) {
            ArchiveTorrents.TorrageWS.cacheTorrentRequest inValue = new ArchiveTorrents.TorrageWS.cacheTorrentRequest();
            inValue.torrent = torrent;
            return ((ArchiveTorrents.TorrageWS.CachePortType)(this)).cacheTorrentAsync(inValue);
        }
    }
}
